# Variables

@baseUrl = http://localhost:3333

# Health Check
GET {{baseUrl}}/health

###

# Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Oseas room's",
  "description": "Puro suco da baguncinha"
}

###

@roomId = b7743b77-be91-4f46-aa95-fa895b5f30fa

###

# Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Room Questions
# @name createRoomQuestions
POST {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json

{
  "questions": "O que é vueJS?"
}